### ISSUE TITLE
check mobile version of demo template

### ISSUE THREAD

**Issue by reusr1** [ez-aem/aem-site-template-tailwind#2]
Improving the mobile styling and template settings for the Wireframe demo site is a needed enhancement from what was implemented in the Adobe Wireframe version - which had no mobile styling or template settings.

The majority of the changes are in the /site folder, making updates to responsive settings of content and components. The header will need custom styling and JavaScript to display and behave like the design. Additionally, decisions for how to add horizontal padding on full-width containers needs to be made.

- [x] Header
  - [x] Implement Toggle Button
    - As style system class on the button element targeting the closest container like in ez-aem?
  - [x] Style header elements according to design
  - [x] Update /site content.xml files in accordance with design
- [x] Footer
  - [x] Style according to design
  - [x] Update .content.xml files with correct responsive settings
- [x] Home Page
  - [x] Update .content.xml files with correct responsive settings
- [x] Article Page
  - [x] Update .content.xml files with correct responsive settings
- [x] Contact Page
  - [x] All text inputs full width
  - [x] Second Column needs to be full width
  - [x] Update .content.xml files with correct responsive settings
 - [x] Full Width Grid horizontal padding
   - ~~Perhaps `.aem-Grid--phone--12: { padding-inline: calc(var(--aem-grid-gap) / 2);`? - No~~
   - ~~[ ] Add as `.responsivegrid:not(.full-width)` instead~~
   - Added `padding-inline: var(--aem-grid-gap)` via configuration in tailwind.config.js that's added to largest grid setting
 - [x] Update all policies and .content.xml files with responsive settings
 - [x] See if it's possible to have a 4 column grid on mobile like the design requests
   - ~~It's not.~~
   - There's a semi-hacky way to do it, but for now, not worth it
 - [x] Fix language navigation dropdown to go up instead of down on mobile menu

**Comment by jzeltman** [comment]
[ ] Header
[ ] Footer
[ ] Home Page
[ ] Article Page
[ ] Contact Page
  [ ] All text inputs full width
  [ ] Second Column needs to be full width
 [ ] Full Width Grid horizontal padding
  - Perhaps `.aem-Grid--phone--12: { padding-inline: calc(var(--aem-grid-gap) / 2);`?

**Comment by jzeltman** [comment]
All of the above issues have been resolved, and also the mobile webkit bug.
