### ISSUE TITLE
better readme for downloaded theme

### ISSUE THREAD

**Issue by reusr1** [ez-aem/aem-site-template-tailwind#3]
Add readme documentation to help users get started quickly.

- [x] Experience League for building site templates
- [x] Videos for building site templates
- [x] Documentation on how to design for Core Components
- [x] aemcomponents.dev
- [x] WKND.site?
- [ ] Link to a page that explains how to integrate a site theme with custom components
- [x] AEM Site Template Builder
- [x] Link to upstream AEM Site Template Standard?
- [x] Tailwind
- [x] Parcel
- [x] PostCSS
- [x] TypeScript
- [x] Prettier
- [x] ESLint
- [ ] How to add custom fonts
- [ ] How to add images
- [ ] Links to EZ-AEM upselling opportunities
- [x] Tailwind IDE Plugins - for VSCode, NeoVim, 
- [x] Headwind VSCode Plugin

**Comment by jzeltman** [comment]
I don't think there are currently links available for articles on how to integrate with custom components. Perhaps that something that we could write in the future. But I don't think is a blocker for 1.2.2

**Comment by reusr1** [comment]
agree

**Comment by jzeltman** [comment]
The downloaded theme readme has been improved
