### ISSUE TITLE
may be a good idea to go to a initial page with docs upon creating the site

### ISSUE THREAD

**Issue by reusr1** [ez-aem/aem-site-template-tailwind#4]
Add a documentation page as the 'open' page after site creation. This page should give the author/user a sense of how to use the site template, next steps, recommendations, and perhaps upselling opportunities for paid ez-aem.

- [x] Add a documentation page as the default page that's opened
  - [x] Make it hidden from search and navigation
  - [x] Update the package.json to point to this page
  - [x] Explain how to download the site theme for frontend customization
  - [x] Link to a page that explains how to integrate a site theme with custom components
    - This will have to come in the future, as this documentation/articles don't exist yet
- [x] Update contact page content so the form submits to an appropriate headwire address for lead generation

**Comment by jzeltman** [comment]
Initial docs have been added
