### ISSUE TITLE
Bug: AEM Experience Fragments do not load fonts/images from theme/resources

### ISSUE THREAD

**Issue by jzeltman** [ez-aem/aem-site-template-tailwind#6]
![image](https://user-images.githubusercontent.com/200346/147964971-942c9eb2-1d50-48fd-b769-fe6c8bcc2935.png)

**Comment by ishaanbedi** [comment]
Hey! Can I work on this ?

**Comment by jzeltman** [comment]
@ishaanbedi I will be pushing an update to the header styling for mobile today. If this issue persists afterwards, then would love some help :)

**Comment by jzeltman** [comment]
@ishaanbedi 
![image](https://user-images.githubusercontent.com/200346/148123742-db0f571a-e1a3-4ffc-851c-e693241dd13e.png)

^ This is the current status after today's work on the mobile styling.

The issue with the fonts also effects images that come from the theme/resources. In the case of the mobile header, it effects the background images used on the button that toggles the mobile menu. I believe this to be a bug with AEM and not with the template. I've tested and duplicated the experience on the adobe/aem-site-template-standard template.

As for the alignment, it happens due to the AEM author dialogs that are used to add new components. I don't see an easy way to overcome this. Additionally, it would result in extra CSS that would be shipped to end users, that only would be seen by the authors. Therefore I think it's not worth the effort or extra bytes of CSS. 

The fonts and images not working is likely a bug though, and a bug with AEM or Quick Sites. I'm waiting to hear back from some people at Adobe.

**Comment by jzeltman** [comment]
This has been logged with the official [adobe/aem-site-template-basic](https://github.com/adobe/aem-site-template-basic) repo, as it is a bug within AEM, and not the templates. [Issue #74](https://github.com/adobe/aem-site-template-standard/issues/74)
